### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by ghost** [awsaaaq/GoBP#4]
Generating cobalt strike 64 bit will report an error in some windwos2012, indicating incompatibility. For example: This version of d:\oracle\system exe is not compatible with the version of Windows you're running.

![图片](https://user-images.githubusercontent.com/97148326/179367498-ca0d74af-a44e-4f60-a1e3-d4c597887bb9.png)

**Comment by awsaaaq** [comment]
Maybe it's because go can't run in windows server 2012
