### ISSUE TITLE
没有生成GoBP.exe

### ISSUE THREAD

**Issue by diaomina** [awsaaaq/GoBP#9]
运行 `main.exe` 后，并没有生成GoBP.exe
![image](https://user-images.githubusercontent.com/40923075/183288524-306195ef-f011-46e8-a1dc-63c02568ec1b.png)

**Comment by diaomina** [comment]
![image](https://user-images.githubusercontent.com/40923075/183288723-0831e36d-7f59-43af-9fc7-775c4978d73d.png)

**Comment by diaomina** [comment]
![image](https://user-images.githubusercontent.com/40923075/183288755-68551a4f-876e-406c-8816-10f4753875bf.png)

**Comment by awsaaaq** [comment]
I had update my release.And you need to go get some module as readme said.

**Comment by diaomina** [comment]
Hi，我使用v2.0.1依然有些问题，求助：

已经运行了`go get`
![image](https://user-images.githubusercontent.com/40923075/183829417-80e40d57-6993-46f2-a558-c1df58db218d.png)

但是还是报错：
![image](https://user-images.githubusercontent.com/40923075/183829069-ccb0fafd-859f-4194-a078-b54d5f29683d.png)

并且后面删除了`go.mod`与`go.sum`文件，重新初始化生成，依旧不行
![image](https://user-images.githubusercontent.com/40923075/183829358-12bf4370-2e8e-4927-b437-ed93af744ef2.png)

**Comment by awsaaaq** [comment]
Maybe you had seen a dir named "temp" and you can find the template Gorun.go.So you can try to build,debug and fix it.And then use go-strip.exe to  obfuscate it.
